# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MDS <- function(D, Theta, n_epoch, step_size, tot, seed) {
    .Call('_ProcData_MDS', PACKAGE = 'ProcData', D, Theta, n_epoch, step_size, tot, seed)
}

MDS_subset <- function(D, Theta, n_epoch, step_size, tot, train_set, valid_set) {
    .Call('_ProcData_MDS_subset', PACKAGE = 'ProcData', D, Theta, n_epoch, step_size, tot, train_set, valid_set)
}

