# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculate_dissimilarity_cpp <- function(seq1, seq2) {
    .Call('_ProcData_calculate_dissimilarity_cpp', PACKAGE = 'ProcData', seq1, seq2)
}

calculate_tdissimilarity_cpp <- function(seq1, seq2, ts1, ts2) {
    .Call('_ProcData_calculate_tdissimilarity_cpp', PACKAGE = 'ProcData', seq1, seq2, ts1, ts2)
}

group_score_cpp <- function(list1, list2) {
    .Call('_ProcData_group_score_cpp', PACKAGE = 'ProcData', list1, list2)
}

#' Calculate "oss_action" dissimilarity matrix through Rcpp
#' @param seqs a list of action sequences
#' @return \code{calculate_dist_cpp} returns the "oss_action" dissimilarity matrix of 
#' the action sequences in \code{seqs}.
#' @export
calculate_dist_cpp <- function(seqs) {
    .Call('_ProcData_calculate_dist_cpp', PACKAGE = 'ProcData', seqs)
}

calculate_tdist_cpp <- function(action_seqs, time_seqs) {
    .Call('_ProcData_calculate_tdist_cpp', PACKAGE = 'ProcData', action_seqs, time_seqs)
}

calculate_group_dist_cpp <- function(seqs) {
    .Call('_ProcData_calculate_group_dist_cpp', PACKAGE = 'ProcData', seqs)
}

calculate_common_event_proportion <- function(seq1, seq2) {
    .Call('_ProcData_calculate_common_event_proportion', PACKAGE = 'ProcData', seq1, seq2)
}

paste_seq <- function(seq, k) {
    .Call('_ProcData_paste_seq', PACKAGE = 'ProcData', seq, k)
}

calculate_common_ngram_proportion <- function(seq1, seq2, k) {
    .Call('_ProcData_calculate_common_ngram_proportion', PACKAGE = 'ProcData', seq1, seq2, k)
}

calculate_ngram_dissimilarity <- function(seq1, seq2, L_set) {
    .Call('_ProcData_calculate_ngram_dissimilarity', PACKAGE = 'ProcData', seq1, seq2, L_set)
}

calculate_ngram_dist_cpp <- function(seqs, L_set) {
    .Call('_ProcData_calculate_ngram_dist_cpp', PACKAGE = 'ProcData', seqs, L_set)
}

MDS <- function(D, Theta, n_epoch, step_size, tot, seed) {
    .Call('_ProcData_MDS', PACKAGE = 'ProcData', D, Theta, n_epoch, step_size, tot, seed)
}

MDS_subset <- function(D, Theta, n_epoch, step_size, tot, train_set, valid_set) {
    .Call('_ProcData_MDS_subset', PACKAGE = 'ProcData', D, Theta, n_epoch, step_size, tot, train_set, valid_set)
}

